### ISSUE TITLE
ADD DSA folders with ROADMAPS AND TUTORIA VIDEO LINKS (HACKTBERFEST 2022)

### ISSUE THREAD

**Issue by sam-tripathi** [sam-tripathi/Defeat-JAVA#1]
Create a DSA folder and add sub-sections, topic wise topic explanations with code.

**Comment by swapn652** [comment]
Do you want links to videos and sites that explain those topics, or want handwritten notes with code and diagrams? The latter would take too much time. Probably more than a month or so, unless someone has already created some really clean notes.

**Comment by sam-tripathi** [comment]
Yes

**Comment by sam-tripathi** [comment]
Yes , I want all possible things ehich could help beginners in learning java

**Comment by swapn652** [comment]
Assign me, I will try to work on it. I have pretty decent ideas about Java resources, as I myself code in Java

**Comment by sam-tripathi** [comment]
OK you can work on it 
If you know then you can contribute 
You can also forward it to your other friends
who have good knowledge of resurces

**Comment by sam-tripathi** [comment]
if you want you can also add any java project for beginners in the project section i have created anther issue for that you may look out .

**Comment by Faizan96322** [comment]
hey, I would like to contribute to this issue
I would work on a few more DSA problems with their solutions in python,
hoping to get assigned to this task asap!

**Comment by sam-tripathi** [comment]
> hey, I would like to contribute to this issue
> I would work on a few more DSA problems with their solutions in python,
> hoping to get assigned to this task asap!

Ok work on it

**Comment by nikitadudhbhate** [comment]
hi, @sam-tripathi I'm a newbie in the open-source contribution, I have one repo of DSA with basic to advance, with Problems, and Video links. it's Kunal Kushwaha's Repo and opensource file. can I contribute?

**Comment by sam-tripathi** [comment]
yes you  can
