### ISSUE TITLE
Longest Consecutive sequence question using Hashmap Datastructure

### ISSUE THREAD

**Issue by kfayazuddin** [sam-tripathi/Defeat-JAVA#141]
I want to solve this import question using Hashmap,
 which help user to again understanding :
1.)inbuild function of Hashmap
2.) Understand of question solution through  Hashmap and with Time complexity O(n);
using searching array it makes the tim complexity O(n^2).
3.)Optimised Code

**Comment by sam-tripathi** [comment]
Ok then work on it

**Comment by kfayazuddin** [comment]
Thanks for assigning.

**Comment by kfayazuddin** [comment]
Hi  i have solved this issue #141
Please merge it .

Thank you
