### ISSUE TITLE
Create A PROBEM folder along with a SOLUTION folder

### ISSUE THREAD

**Issue by sam-tripathi** [sam-tripathi/Defeat-JAVA#2]
Create a folder named 'PROBLEMS' and add sets of questions topic-wise and in the other folder named 'SOLUTION' add solutions to the sets of problems.

**Comment by Niravprajapati1** [comment]
Can i contribute to this ?

**Comment by sam-tripathi** [comment]
> Can i contribute to this ?

Yeh you can 

it is ment to be contributed
you can also sign for hacktober fest

**Comment by Niravprajapati1** [comment]
Sure it's my pleasure.

**Comment by nikitadudhbhate** [comment]
hi @sam-tripathi I'm a newbie in the open-source contribution, I created one folder on the Condition problem of various math formulas with the code solution using condition concept it's beginner-friendly code.
