### ISSUE TITLE
Adding a Gui based digital clock in java

### ISSUE THREAD

**Issue by sasidharswarangi** [sam-tripathi/Defeat-JAVA#25]
A simple program for digital clock GUI

want to work on this under #hacktober2022

**Comment by rutuja1121** [comment]
Can I work on this issue?

**Comment by sasidharswarangi** [comment]
had to change the simple java project as someone has already implemented it in the main branch

**Comment by sam-tripathi** [comment]
ok

**Comment by sasidharswarangi** [comment]
Created a PR under #34
