### ISSUE TITLE
CUSTOMIZE AND  ORGANIZE THE INTRODUCTION

### ISSUE THREAD

**Issue by sam-tripathi** [sam-tripathi/Defeat-JAVA#3]
Organize and Customize the introduction folder to make the repository organised for new learners.
NOTE: must read all the issues to understand the aim of the projects clearly.

**Comment by sam-tripathi** [comment]
OK WORK ON IT

**Comment by achiverram28** [comment]
Bro I have done the Pr , can you look at it
