### ISSUE TITLE
DSA - Add sorting algorithms

### ISSUE THREAD

**Issue by Baba-Yaga-1** [sam-tripathi/Defeat-JAVA#37]
I want to add bubble sort , selection sort and insertion sort.
Can you assign me this issue?
I am a hacktoberfest contributor.

**Comment by anirudh0806** [comment]
Assign me this issue

**Comment by Baba-Yaga-1** [comment]
@sam-tripathi Under which folder am I supposed to add the searching algorithms or should I create a new folder separately?

**Comment by sam-tripathi** [comment]
beginners java folder inside folders

**Comment by TangoBeee** [comment]
Hey
Would you like to entrust this issue to me?
I will add some algorithms like sorting algorithm (bubble sort, selection sort, insertion sort, quick sort, and merge sort) and also binary search and two pointer algorithm and I will also add some questions related to these algorithms.

**Comment by sam-tripathi** [comment]
> Hey Would you like to entrust this issue to me? I will add some algorithms like sorting algorithm (bubble sort, selection sort, insertion sort, quick sort, and merge sort) and also binary search and two pointer algorithm and I will also add some questions related to these algorithms.

kk try but don't repeat programs that already exist like bubble sort etc.

**Comment by achiverram28** [comment]
Dude , please also assign this to me

**Comment by YlanNaly** [comment]
I want to work with this too Dude
