### ISSUE TITLE
DSA - Added CodeChef Solutions

### ISSUE THREAD

**Issue by arnavgupta2003** [sam-tripathi/Defeat-JAVA#40]
Added 121 selected problems from CodeChef with solutions 
Difficulty Ranges from 300 to 1900

**Comment by arnavgupta2003** [comment]
Assign this to me.. I'll create a pull request then you can merge

**Comment by sam-tripathi** [comment]
#assigned you now zyou can do

**Comment by arnavgupta2003** [comment]
@sam-tripathi Created a pull request..
Accept request to merge.

**Comment by arnavgupta2003** [comment]
Do add the tag hacktoberfest in the pull request
