### ISSUE TITLE
Adding BMI Calculator using Java

### ISSUE THREAD

**Issue by LiQuiD-404** [sam-tripathi/Defeat-JAVA#9]
A simple java program which can compute a user's BMI based on his height and weight.

I will be working on this issue under hacktoberfest'22

**Comment by sasidharswarangi** [comment]
I would like to work on this

**Comment by sasidharswarangi** [comment]
please assign me this

**Comment by LiQuiD-404** [comment]
@sam-tripathi please assign me this issue so that I can start working on it.

**Comment by sam-tripathi** [comment]
ok do this

**Comment by LiQuiD-404** [comment]
@sam-tripathi you haven’t assigned me thsi issue

**Comment by minhaj-313** [comment]
@sam-tripathi I want to add BMI Calculator using Java. with the help of this Program, we can calculate Body Mass Index.
I want to contribute to Your Project Under ( Hacktoberfest 2022 ) Can you please Assign it to me?
Thank You In Advance.

**Comment by LiQuiD-404** [comment]
@minhaj-313 Sorry but I am already working on this issue. Kindly make a new issue

**Comment by sam-tripathi** [comment]
hi, Liquid I visited your profile and now I wanna know how did you make such an awesome profile?
and stats representation is just amazing.  Could you help me in building stats like yours which site did you used?

**Comment by anirudh0806** [comment]
I want to contribute. Please assign

**Comment by LiQuiD-404** [comment]
@sam-tripathi 
![image](https://user-images.githubusercontent.com/94376674/193540796-c4e6a235-e00e-4113-9fb6-830867e0fc6c.png)
Kindly have a look at it.

**Comment by LiQuiD-404** [comment]
> hi, Liquid I visited your profile and now I wanna know how did you make such an awesome profile? and stats representation is just amazing. Could you help me in building stats like yours which site did you used?

Thank you so much for your kind words. Sure I will share with you the resources I used to make my profile.

**Comment by sam-tripathi** [comment]
> @sam-tripathi 
> ![image](https://user-images.githubusercontent.com/94376674/193540796-c4e6a235-e00e-4113-9fb6-830867e0fc6c.png)
> Kindly have a look at it.

Bro i think i was a glitch kind thing ,i have re entered the tags once check again after sometime

**Comment by LiQuiD-404** [comment]
I guess you have to add "hacktoberfest-accepted" tag to the issues. @sam-tripathi

**Comment by sam-tripathi** [comment]
> I guess you have to add "hacktoberfest-accepted" tag to the issues. @sam-tripathi

Done bro
