### ISSUE TITLE
Add OOPs Concepts in JAVA

### ISSUE THREAD

**Issue by Shivay10th** [sam-tripathi/Defeat-JAVA#96]
I can add OOPs Concepts implementation in this repository.

**Comment by sam-tripathi** [comment]
are you working on this issue?

**Comment by Shivay10th** [comment]
yup

**Comment by Tishachhabra** [comment]
can i contribute in this too?

**Comment by sam-tripathi** [comment]
> can i contribute in this too?

yeh you can

**Comment by Tishachhabra** [comment]
Do I have to add such files under a specific folder or make a new one for OOPs?

**Comment by ArcheR1901** [comment]
Hi, can I work on this one?

**Comment by YlanNaly** [comment]
Can i work  with this too ?
